### ISSUE TITLE
Fix glibc-2.27

### ISSUE THREAD

**Issue by david942j** [david942j/heapinfo#16]
Buggy because of structure `malloc_state` changed

**Comment by david942j** [comment]
and `get_arena.c` broken because of tcache

**Comment by matrix1001** [comment]
what about glibc-2.26? it's odd that glibc-2.26 has the same problem, although the source code of `malloc_state` did not change like glibc-2.27. maybe i got something wrong.

**Comment by david942j** [comment]
glibc-2.26 is in the test list of heapinfo, so it should work fine.
Might because of tcache? I remembered tcache is first introduced in 2.26

**Comment by matrix1001** [comment]
checked. glibc-2.26 32bit has 11 fastbins.
```
glibc-2.26-32-build# gdb malloc/malloc.o
pwndbg: loaded 166 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Set whether to clear the screen before printing the context to True
Reading symbols from malloc/malloc.o...done.
pwndbg> ptype struct malloc_state
type = struct malloc_state {
    __libc_lock_t mutex;
    int flags;
    mfastbinptr fastbinsY[11];
    mchunkptr top;
    mchunkptr last_remainder;
    mchunkptr bins[254];
    unsigned int binmap[4];
    struct malloc_state *next;
    struct malloc_state *next_free;
    size_t attached_threads;
    size_t system_mem;
    size_t max_system_mem;
}
```


so you need to add `main_arena_offset -= 4` to fix.
