### ISSUE TITLE
python version - heapinspect

### ISSUE THREAD

**Issue by matrix1001** [david942j/heapinfo#35]
I am working on it 😀. I used your idea about how to locate the main arena offset. Not finished yet.  [heapinfo](https://github.com/matrix1001/heapinspect)

**Comment by matrix1001** [comment]
@david942j I'm about to finish the main framework. I got a problem with libc-2.27.so (32 bit version). 

check this pic.

![image](https://user-images.githubusercontent.com/32097922/47604805-01029800-da31-11e8-803d-79fa5c7d99ab.png)

the first 8 bytes of the heap are 0, while normally the first 4 bytes should be 0, the second 4 bytes should be size. it is odd. i have test on some 32bit libc-2.27.so, all the same.

however, 64bit libc-2.27.so does not have this. and other 32bit libc below 2.27 do not have this.

have you met this when trying to parse the entire heap?

by the way, parsing the entire heap may be a new useful feature for your project.

**Comment by david942j** [comment]
I guess it's because of the alignment strategy somehow changed in newer glibc?
I know this behavior, but didn't track which change(s) lead to this.
