### ISSUE TITLE
Wrong heap boundary (tcache)

### ISSUE THREAD

**Issue by matrix1001** [david942j/heapinfo#42]
This is a problem caused by wrong heap boundary.

`heapinfo` assumes that `tcache_perthread_struct` lies o the start of the heap. In most cases, there will  be no problem.

Here's where I found this problem.

```
$ gdb /bin/sh
pwndbg> r
pwndbg> vmmap heap
    0x555555771000     0x555555794000 rw-p    23000 0      [heap]
pwndbg> dq 0x555555771000
0000555555771000     0000000000000000 0000000000000000
0000555555771010     0000000000000000 0000000000000000
0000555555771020     0000000000000000 0000000000000000
0000555555771030     0000000000000000 0000000000000000
pwndbg> p __curbrk
$0 = (void *) 0x555555773000
pwndbg> dq 0x555555773000
0000555555773000     0000000000000000 0000000000000251
0000555555773010     0000000100000000 0000000000000000
0000555555773020     0000000000000000 0100000000000000
0000555555773030     0000000000000000 0000000000000000
```

Simply use the start address of heap will miss the correct `tcache_perthread_struct`.

I have checked code in `pwndbg`. `mp_` is used to find the correct `sbrk_base`. link: [get_heap_boundaries](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/heap/ptmalloc.py#L369)

So, here's the problem. How to get `sbrk_base` without `gdb` ?

**Comment by david942j** [comment]
Is this behavior depends on the glibc or the binary?
And it would be great if you can give me tips how to reproduce it.

**Comment by matrix1001** [comment]
Got no idea of how this happened.

I was writing a gdb plugin for my project. And just used gdb to start `/bin/sh`, then found this. Starting `/bin/sh` without gdb does not have this problem. I use `glibc-2.27`.

I think it has something to do with `ld.so`. Somehow, when I use gdb to start `/bin/sh`, `ld.so` makes out a `heap` space.

Also, simply run `gdb /lib64/ld-linux-x86-64.so.2`  and check that it makes out a `heap` area.

**Comment by matrix1001** [comment]
That makes sense. You are right.
